# Generated by Django 4.1.1 on 2022-11-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='adhaar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
