# Generated by Django 4.1.1 on 2022-11-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_product_adhaar_alter_product_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('adhaar', models.CharField(max_length=12)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
