# Generated by Django 4.1.1 on 2022-11-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_complaint_adhaar_alter_complaint_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='adhaar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
