# Generated by Django 4.1.1 on 2022-11-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_lat_location_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('adhaar', models.CharField(max_length=12)),
                ('crime_description', models.TextField()),
            ],
        ),
    ]
