# Generated by Django 4.1.1 on 2022-11-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_witness'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='witness',
            name='address',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
