# Generated by Django 4.1.1 on 2022-11-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_complaint_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ip_address',
            field=models.GenericIPAddressField(default=True),
        ),
    ]
