# Generated by Django 4.1.1 on 2022-11-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_complaint_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
