# Generated by Django 4.1.1 on 2022-11-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_complaint_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='ip_address',
        ),
    ]
